language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install netcdf4 scipy numba
  - pip list

script:
  - make TOPO=seawifs_ocn_mask.nc
  - md5sum *.nc
